FROM amazoncorretto:21
LABEL authors="lcl94"
RUN mkdir /app
WORKDIR /app
COPY target/*.jar /app/app.jar
EXPOSE 8080
ENV SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
ENV SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
ENV SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
ENV SPRING_DATA_REDIS_PASSWORD=${REDIS_PASSWORD}
ENV SPRING_DATA_REDIS_HOST=${REDIS_HOST}
ENV OSS_S3_ACCESSKEY=${OSS_ACCESSKEY}
ENV OSS_S3_SECRETKEY=${OSS_SECRETKEY}
ENV JAVA_OPTS="-Xmx512m -Xms512m -Xmn256m -XX:+UseZGC -XX:MaxGCPauseMillis=200 -XX:ParallelGCThreads=1 -XX:ConcGCThreads=1"
CMD ["sh", "-c", "java $JAVA_OPTS -jar /app/app.jar"]